/* namsa-trip service worker — cache first, offline capable */
const VERSION = "namsa-v202609061707-29424046";
const CORE = VERSION + '-core';
const RUNTIME = VERSION + '-runtime';

const PRECACHE = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  "https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css",
  "./img/atacama--el-tatio-geysers.jpg",
  "./img/atacama--el-tatio-geysers-2.jpg",
  "./img/atacama--el-tatio-geysers-3.jpg",
  "./img/atacama--hero-san-pedro-de-atacama.jpg",
  "./img/atacama--laguna-cejar.jpg",
  "./img/atacama--laguna-cejar-2.jpg",
  "./img/atacama--laguna-cejar-3.jpg",
  "./img/atacama--mood-1.jpg",
  "./img/atacama--mood-2.jpg",
  "./img/atacama--mood-3.jpg",
  "./img/atacama--san-pedro-de-atacama-village.jpg",
  "./img/atacama--san-pedro-de-atacama-village-2.jpg",
  "./img/atacama--san-pedro-de-atacama-village-3.jpg",
  "./img/atacama--valle-de-la-luna-atacama.jpg",
  "./img/atacama--valle-de-la-luna-atacama-2.jpg",
  "./img/atacama--valle-de-la-luna-atacama-3.jpg",
  "./img/cusco--hero-cusco.jpg",
  "./img/cusco--machu-picchu.jpg",
  "./img/cusco--machu-picchu-2.jpg",
  "./img/cusco--machu-picchu-3.jpg",
  "./img/cusco--maras-salt-ponds.jpg",
  "./img/cusco--maras-salt-ponds-2.jpg",
  "./img/cusco--maras-salt-ponds-3.jpg",
  "./img/cusco--mercado-san-pedro-cusco.jpg",
  "./img/cusco--mercado-san-pedro-cusco-2.jpg",
  "./img/cusco--mercado-san-pedro-cusco-3.jpg",
  "./img/cusco--mood-1.jpg",
  "./img/cusco--mood-2.jpg",
  "./img/cusco--mood-3.jpg",
  "./img/cusco--qorikancha.jpg",
  "./img/cusco--qorikancha-2.jpg",
  "./img/cusco--qorikancha-3.jpg",
  "./img/cusco--sacsayhuaman.jpg",
  "./img/cusco--sacsayhuaman-2.jpg",
  "./img/cusco--sacsayhuaman-3.jpg",
  "./img/cusco--san-blas-cusco.jpg",
  "./img/cusco--san-blas-cusco-2.jpg",
  "./img/cusco--san-blas-cusco-3.jpg",
  "./img/cusco--vinicunca-rainbow-mountain.jpg",
  "./img/cusco--vinicunca-rainbow-mountain-2.jpg",
  "./img/cusco--vinicunca-rainbow-mountain-3.jpg",
  "./img/food--aji-de-gallina.jpg",
  "./img/food--alpaca-a-la-parrilla.jpg",
  "./img/food--anticucho.jpg",
  "./img/food--anticuchos.jpg",
  "./img/food--api-con-pastel.jpg",
  "./img/food--arroz-chaufa.jpg",
  "./img/food--arroz-con-leche.jpg",
  "./img/food--asado.jpg",
  "./img/food--caldillo-de-congrio.jpg",
  "./img/food--caldo-de-gallina.jpg",
  "./img/food--carapulcra.jpg",
  "./img/food--carmenere.jpg",
  "./img/food--causa.jpg",
  "./img/food--cazuela.jpg",
  "./img/food--cerveza.jpg",
  "./img/food--ceviche.jpg",
  "./img/food--chairo.jpg",
  "./img/food--chanfainita.jpg",
  "./img/food--chicha-morada.jpg",
  "./img/food--chilcano.jpg",
  "./img/food--chirimoya.jpg",
  "./img/food--chorrillana.jpg",
  "./img/food--chupe-de-camarones.jpg",
  "./img/food--churrasco.jpg",
  "./img/food--completo.jpg",
  "./img/food--cortado.jpg",
  "./img/food--cuy.jpg",
  "./img/food--emoliente.jpg",
  "./img/food--empanada.jpg",
  "./img/food--empanada-de-pino.jpg",
  "./img/food--erizos.jpg",
  "./img/food--humintas.jpg",
  "./img/food--inca-kola.jpg",
  "./img/food--leche-asada.jpg",
  "./img/food--leche-de-tigre.jpg",
  "./img/food--llajua.jpg",
  "./img/food--lomito.jpg",
  "./img/food--lomo-saltado.jpg",
  "./img/food--lucuma.jpg",
  "./img/food--machas-a-la-parmesana.jpg",
  "./img/food--majadito.jpg",
  "./img/food--manjar.jpg",
  "./img/food--maracuya-sour.jpg",
  "./img/food--mate-de-coca.jpg",
  "./img/food--mazamorra-morada.jpg",
  "./img/food--mocochinchi.jpg",
  "./img/food--mote-con-huesillo.jpg",
  "./img/food--muna.jpg",
  "./img/food--pachamanca.jpg",
  "./img/food--paila-marina.jpg",
  "./img/food--papa-a-la-huancaina.jpg",
  "./img/food--pastel-de-choclo.jpg",
  "./img/food--patasca.jpg",
  "./img/food--pebre.jpg",
  "./img/food--picarones.jpg",
  "./img/food--pique-macho.jpg",
  "./img/food--pisco-sour.jpg",
  "./img/food--pisco-sour-con-rica-rica.jpg",
  "./img/food--piure.jpg",
  "./img/food--plato-paceno.jpg",
  "./img/food--pollo-a-la-brasa.jpg",
  "./img/food--rocoto-relleno.jpg",
  "./img/food--salchipapa.jpg",
  "./img/food--saltena.jpg",
  "./img/food--seco-de-cordero.jpg",
  "./img/food--silpancho.jpg",
  "./img/food--singani.jpg",
  "./img/food--sopa-de-mani.jpg",
  "./img/food--sopa-seca.jpg",
  "./img/food--sopaipilla.jpg",
  "./img/food--suspiro-a-la-limena.jpg",
  "./img/food--tacu-tacu.jpg",
  "./img/food--tallarin-saltado.jpg",
  "./img/food--tamal.jpg",
  "./img/food--terremoto.jpg",
  "./img/food--tiradito.jpg",
  "./img/food--trucha-frita.jpg",
  "./img/food--tucumana.jpg",
  "./img/ica--ballestas-islands.jpg",
  "./img/ica--ballestas-islands-2.jpg",
  "./img/ica--ballestas-islands-3.jpg",
  "./img/ica--hero-huacachina.jpg",
  "./img/ica--huacachina-oasis.jpg",
  "./img/ica--huacachina-oasis-2.jpg",
  "./img/ica--huacachina-oasis-3.jpg",
  "./img/ica--ica-desert-dunes.jpg",
  "./img/ica--ica-desert-dunes-2.jpg",
  "./img/ica--ica-desert-dunes-3.jpg",
  "./img/ica--ica-pisco-bodega.jpg",
  "./img/ica--mood-1.jpg",
  "./img/ica--nazca-lines.jpg",
  "./img/ica--nazca-lines-2.jpg",
  "./img/ica--nazca-lines-3.jpg",
  "./img/ica--paracas-national-reserve.jpg",
  "./img/ica--paracas-national-reserve-2.jpg",
  "./img/ica--paracas-national-reserve-3.jpg",
  "./img/intro--hero-machu-picchu-andes.jpg",
  "./img/lapaz--cholita-wrestling-el-alto.jpg",
  "./img/lapaz--cholita-wrestling-el-alto-2.jpg",
  "./img/lapaz--cholita-wrestling-el-alto-3.jpg",
  "./img/lapaz--hero-la-paz.jpg",
  "./img/lapaz--mi-teleferico-la-paz.jpg",
  "./img/lapaz--mood-1.jpg",
  "./img/lapaz--mood-2.jpg",
  "./img/lapaz--mood-3.jpg",
  "./img/lapaz--plaza-murillo.jpg",
  "./img/lapaz--plaza-murillo-2.jpg",
  "./img/lapaz--plaza-murillo-3.jpg",
  "./img/lapaz--tiwanaku.jpg",
  "./img/lapaz--tiwanaku-2.jpg",
  "./img/lapaz--tiwanaku-3.jpg",
  "./img/lapaz--valle-de-la-luna-la-paz.jpg",
  "./img/lapaz--valle-de-la-luna-la-paz-2.jpg",
  "./img/lapaz--valle-de-la-luna-la-paz-3.jpg",
  "./img/lapaz--witches-market-la-paz.jpg",
  "./img/lapaz--witches-market-la-paz-2.jpg",
  "./img/lapaz--witches-market-la-paz-3.jpg",
  "./img/lima--barranco-lima.jpg",
  "./img/lima--barranco-lima-2.jpg",
  "./img/lima--barranco-lima-3.jpg",
  "./img/lima--hero-lima.jpg",
  "./img/lima--huaca-pucllana.jpg",
  "./img/lima--huaca-pucllana-2.jpg",
  "./img/lima--huaca-pucllana-3.jpg",
  "./img/lima--larcomar-miraflores.jpg",
  "./img/lima--larcomar-miraflores-2.jpg",
  "./img/lima--larcomar-miraflores-3.jpg",
  "./img/lima--magic-water-circuit-lima.jpg",
  "./img/lima--magic-water-circuit-lima-2.jpg",
  "./img/lima--magic-water-circuit-lima-3.jpg",
  "./img/lima--mood-2.jpg",
  "./img/lima--mood-3.jpg",
  "./img/lima--plaza-mayor-de-lima.jpg",
  "./img/lima--plaza-mayor-de-lima-2.jpg",
  "./img/lima--plaza-mayor-de-lima-3.jpg",
  "./img/opt--airport.jpg",
  "./img/opt--airport-2.jpg",
  "./img/opt--ballestas-2.jpg",
  "./img/opt--barranco-2.jpg",
  "./img/opt--boleto.jpg",
  "./img/opt--boleto-2.jpg",
  "./img/opt--cholitas-2.jpg",
  "./img/opt--conchaytoro.jpg",
  "./img/opt--conchaytoro-2.jpg",
  "./img/opt--coricancha-2.jpg",
  "./img/opt--larco.jpg",
  "./img/opt--larco-2.jpg",
  "./img/opt--limacentro-2.jpg",
  "./img/opt--lostcanyon.jpg",
  "./img/opt--lostcanyon-2.jpg",
  "./img/opt--magicwater-2.jpg",
  "./img/opt--sacredvalley-2.jpg",
  "./img/opt--sacsayhuaman-2.jpg",
  "./img/opt--sancristobal-2.jpg",
  "./img/opt--santiagocentro-2.jpg",
  "./img/opt--sillustani-2.jpg",
  "./img/opt--skycostanera.jpg",
  "./img/opt--skycostanera-2.jpg",
  "./img/opt--tiwanaku-2.jpg",
  "./img/opt--uros-2.jpg",
  "./img/opt--vinicunca-2.jpg",
  "./img/opt--witches-2.jpg",
  "./img/puno--hero-lake-titicaca-puno.jpg",
  "./img/puno--mood-1.jpg",
  "./img/puno--mood-2.jpg",
  "./img/puno--mood-3.jpg",
  "./img/puno--sillustani.jpg",
  "./img/puno--sillustani-2.jpg",
  "./img/puno--sillustani-3.jpg",
  "./img/puno--taquile-island.jpg",
  "./img/puno--taquile-island-2.jpg",
  "./img/puno--taquile-island-3.jpg",
  "./img/puno--uros-floating-islands.jpg",
  "./img/puno--uros-floating-islands-2.jpg",
  "./img/puno--uros-floating-islands-3.jpg",
  "./img/route--andahuaylillas.jpg",
  "./img/route--chincha.jpg",
  "./img/route--chuquicamata.jpg",
  "./img/route--colchani.jpg",
  "./img/route--cordillera-de-la-sal.jpg",
  "./img/route--la-raya.jpg",
  "./img/route--laguna-colorada.jpg",
  "./img/route--laguna-verde.jpg",
  "./img/route--licancabur.jpg",
  "./img/route--pachacamac.jpg",
  "./img/route--raqchi.jpg",
  "./img/route--sol-de-manana.jpg",
  "./img/santiago--barrio-bellavista-santiago.jpg",
  "./img/santiago--barrio-bellavista-santiago-2.jpg",
  "./img/santiago--barrio-bellavista-santiago-3.jpg",
  "./img/santiago--cerro-san-cristobal.jpg",
  "./img/santiago--cerro-san-cristobal-2.jpg",
  "./img/santiago--cerro-san-cristobal-3.jpg",
  "./img/santiago--cerro-santa-lucia.jpg",
  "./img/santiago--cerro-santa-lucia-2.jpg",
  "./img/santiago--cerro-santa-lucia-3.jpg",
  "./img/santiago--hero-santiago-chile.jpg",
  "./img/santiago--la-chascona.jpg",
  "./img/santiago--la-chascona-2.jpg",
  "./img/santiago--la-chascona-3.jpg",
  "./img/santiago--mercado-central-santiago.jpg",
  "./img/santiago--mercado-central-santiago-2.jpg",
  "./img/santiago--mercado-central-santiago-3.jpg",
  "./img/santiago--mood-3.jpg",
  "./img/santiago--plaza-de-armas-santiago.jpg",
  "./img/santiago--plaza-de-armas-santiago-2.jpg",
  "./img/santiago--plaza-de-armas-santiago-3.jpg",
  "./img/uyuni--hero-salar-de-uyuni.jpg",
  "./img/uyuni--incahuasi-island.jpg",
  "./img/uyuni--incahuasi-island-2.jpg",
  "./img/uyuni--incahuasi-island-3.jpg",
  "./img/uyuni--laguna-colorada.jpg",
  "./img/uyuni--laguna-colorada-2.jpg",
  "./img/uyuni--laguna-colorada-3.jpg",
  "./img/uyuni--mood-1.jpg",
  "./img/uyuni--mood-2.jpg",
  "./img/uyuni--mood-3.jpg",
  "./img/uyuni--salar-de-uyuni-salt-flat.jpg",
  "./img/uyuni--salar-de-uyuni-salt-flat-2.jpg",
  "./img/uyuni--salar-de-uyuni-salt-flat-3.jpg",
  "./img/uyuni--termas-de-polques.jpg",
  "./img/uyuni--termas-de-polques-2.jpg",
  "./img/uyuni--uyuni-train-cemetery.jpg",
  "./img/uyuni--uyuni-train-cemetery-2.jpg",
  "./img/uyuni--uyuni-train-cemetery-3.jpg",
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CORE)
      .then(function (c) {
        return Promise.all(PRECACHE.map(function (u) {
          return c.add(new Request(u, { cache: 'reload' })).catch(function () {});
        }));
      })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) {
        return k !== CORE && k !== RUNTIME;
      }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  var isCDN = url.hostname === 'cdn.jsdelivr.net' || url.hostname === 'fonts.gstatic.com';
  if (!isCDN && url.origin !== self.location.origin) return;

  // Navigations resolve to the cached shell so deep hash links work offline.
  if (req.mode === 'navigate') {
    e.respondWith(
      caches.match('./index.html').then(function (hit) {
        return hit || fetch(req).catch(function () { return caches.match('./'); });
      })
    );
    return;
  }

  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && (res.ok || res.type === 'opaque')) {
          var copy = res.clone();
          caches.open(isCDN ? RUNTIME : CORE).then(function (c) {
            c.put(req, copy);
          }).catch(function () {});
        }
        return res;
      }).catch(function () { return caches.match('./index.html'); });
    })
  );
});
